before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: gDRSNXojttbtaNFYt5cZ/e4SmIChR4Ym725b93s8uru8CDjHkCafZxNIvGQaNUd5I3OzFQtXmmt8kjlkxC4HmIFIocQ/j3TQvqxizdbYSJxBxAn5Crb/Ap7hYKiG+9BOHSJjUY1AqpwVu75dZEWqVnC6mbZHdipZishtG+Js4vBnfbVyt85BEydI4u3e8dI80I02Dl8mw2hlCgnPwBQCnWnfCQjvTBeSzij9U8R/6GRGCQ14KPVVU5XQCsmNNNPkmkDfjuL8WO/zq69voLQA0nt9MeqXCjKH1F0iax1cdDwaF5TYoWIDfbaNQMOjtqEqkN8eHx2kEjAWiFL7Fk8SHkYHh26upNQpQW9t/jawly8UNo7DSe9URpkobt9Br/YpYZ85hVj1Eh6Xa9Dz+xWRSsaE2lRhP3aGjd9xie+w5dJ1l5PEsTV/eDfQZQbD9nonzPRrO81saqgaWiIqbaCi8f9wxTVklBbjUEM/EwLj3iI2aYvICcaraMA4T9+0vkOTUNUeqRVw5ggWiL89I2mRqkkF1jj/8jAb6T2sysfxrgkjbSvhnGgYwizvvFdg+Q4NuZoZeDdAr6iv8msjEgMJqSwFMdI60PLhNiCcMmHkh0smVXaqfTQRjBz4BDiIEFgMmfPzzShpCpLFOgDaZy2+8YCNR0MixjH9WFI+Dcv5qus= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
